<a href="https://colab.research.google.com/github/EderDataDriven/EderDataDriven/blob/main/Python_Librerias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerias

Las librerias (o paquetes) son colecciones de funciones, métodos y objetos desarrollados por terceras personas, pero que pueden ser utilizadas por cualquier persona que posea Python, y que buscan atacar una necesidad de análisis específica.

Como se mencionó, este aspecto constituye una importante fortaleza de los lenguajes open source.

En este curso, se utilizarán distintas librerias, entre las que se destacan

* numpy: análisis numérico
* pandas: manipulacion de tablas de datos
* matplotlib: visualización

Empecemos conociendo un poco de numpy, y aprovechemos para saber como importar (o cargar) una libreria en Python

In [5]:
# Importamos la libreria:
import numpy as np

Objeto ndarray

In [3]:
# Crear una lista de listas:
compras = [ ['Cebolla', 'Tomate', 'Papa'], ['Naranjas', 'Manzanas', 'Peras'], ['Aceite', 'Sal', 'Condimentos'], ['Detergente', 'Jabon', 'Shampoo'] ]
print(compras)
print(type(compras))

[['Cebolla', 'Tomate', 'Papa'], ['Naranjas', 'Manzanas', 'Peras'], ['Aceite', 'Sal', 'Condimentos'], ['Detergente', 'Jabon', 'Shampoo']]
<class 'list'>


In [9]:
# Transformamos la lista en arreglo:
compras_array = np.array(compras)
print(compras_array)
print(type(compras_array))

[['Cebolla' 'Tomate' 'Papa']
 ['Naranjas' 'Manzanas' 'Peras']
 ['Aceite' 'Sal' 'Condimentos']
 ['Detergente' 'Jabon' 'Shampoo']]
<class 'numpy.ndarray'>


In [10]:
compras_array.ndim

2

In [11]:
compras_array.shape

(4, 3)

In [12]:
# Cambiar las dimensiones del array:
compras_array.reshape(6,2)

array([['Cebolla', 'Tomate'],
       ['Papa', 'Naranjas'],
       ['Manzanas', 'Peras'],
       ['Aceite', 'Sal'],
       ['Condimentos', 'Detergente'],
       ['Jabon', 'Shampoo']], dtype='<U11')

In [13]:
# Combertir dimensiones a una sola fila:
compras_array.flatten()

array(['Cebolla', 'Tomate', 'Papa', 'Naranjas', 'Manzanas', 'Peras',
       'Aceite', 'Sal', 'Condimentos', 'Detergente', 'Jabon', 'Shampoo'],
      dtype='<U11')

In [17]:
arr = np.array([10,2,9,17])
arr.sort()
print(arr)

[ 2  9 10 17]


In [18]:
arr.size

4

In [19]:
len(arr)

4

## Funciones Matemáticas en NumPy

In [21]:
# Crear 2 arreglos numericos
a1 = np.array([9,7,5,2,1,6,9])
a2 = np.array([8,3,1,9,0,2,1])
print(a1)
print(a2)

[9 7 5 2 1 6 9]
[8 3 1 9 0 2 1]
